# Generated by Django 3.0.2 on 2020-02-25 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('last_opened', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField(max_length=256)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('json_board', models.TextField(default='{}', max_length=102400)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='my_users.MyUser')),
            ],
        ),
    ]
