# Generated by Django 3.0.2 on 2020-02-12 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='last_opened',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 12, 21, 0, 43, 898368)),
            preserve_default=False,
        ),
    ]
