# Generated by Django 3.0.2 on 2020-02-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='json_board',
            field=models.TextField(default='{}', max_length=204800),
        ),
    ]
