# Generated by Django 3.0.2 on 2020-02-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20200216_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='json_board',
            field=models.TextField(default='{}', max_length=10240),
        ),
    ]
