# Generated by Django 3.0.2 on 2020-02-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_owner'),
        ('boards', '0002_board_last_opened'),
    ]

    operations = [
    ]
