# Generated by Django 3.0.2 on 2020-03-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20200308_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='users',
            field=models.TextField(default='<django.db.models.fields.related.ForeignKey>', max_length=500),
        ),
    ]
