# Generated by Django 3.0.2 on 2020-03-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20200308_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='users',
            field=models.TextField(default='', max_length=500),
        ),
    ]
