# Generated by Django 3.0.2 on 2020-03-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20200309_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='json_board',
            field=models.TextField(default='[]', max_length=102400),
        ),
        migrations.AlterField(
            model_name='board',
            name='users',
            field=models.TextField(default='[]', max_length=500),
        ),
    ]
