# Generated by Django 3.0.2 on 2020-04-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_auto_20200413_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='permissions',
            field=models.TextField(default='[]', max_length=500),
        ),
    ]
