# Generated by Django 3.0.5 on 2020-04-19 13:42

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_board_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='thumbnail_picture',
            field=models.ImageField(default=None, max_length=500, upload_to=boards.models.board_dir_path),
            preserve_default=False,
        ),
    ]
