# Generated by Django 3.0.5 on 2020-04-19 13:43

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_board_thumbnail_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='thumbnail_picture',
            field=models.ImageField(default=None, max_length=500, upload_to=boards.models.board_dir_path),
        ),
    ]
