# Generated by Django 3.0.5 on 2020-04-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_auto_20200419_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='thumbnail_picture',
        ),
    ]
