# Generated by Django 3.0.2 on 2020-02-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='password',
            new_name='pw',
        ),
    ]
