# Generated by Django 3.0.2 on 2020-03-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0002_myuser_boards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='boards',
            field=models.TextField(default='{}', max_length=500),
        ),
    ]
