# Generated by Django 3.0.2 on 2020-02-13 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_last_opened'),
        ('my_users', '0003_auto_20200205_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='boards',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='boards.Board'),
        ),
    ]
