# Generated by Django 3.0.2 on 2020-02-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0004_myuser_boards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='boards',
        ),
    ]
