# Generated by Django 3.0.2 on 2020-03-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0004_auto_20200308_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='boards',
        ),
    ]
