# Generated by Django 3.0.2 on 2020-04-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0005_remove_myuser_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='notifications',
            field=models.TextField(default='[]', max_length=500),
        ),
    ]
